openapi: 3.0.0
info:
  title: Search API
  version: 1.0.0
servers:
  - url: http://localhost:4001/search-service
paths:
  /search:
    get:
      summary: Returns a batch of users.
      parameters:
        - name: query
          in: query
          required: true
          description: The search query.
          schema:
            type: string
      responses:
        "200":
          description: Results found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SearchResult"
components:
  schemas:
    SearchResult:
      type: object
      properties:
        type:
          type: string
          enum:
            - product
            - user
        id:
          type: number
